[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

# Для SPA (если используете React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Для фавикона (если у вас my.ico)
[[redirects]]
  from = "/my.ico"
  to = "/favicon.ico"
  status = 200